name: Slither Analysis

on:
    push:
    pull_request:

permissions:
  contents: read

jobs:
    analyze:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
              with:
                egress-policy: audit

            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Run Slither
              uses: crytic/slither-action@b52cc1cbfee9ca3e8722dd5224299d16c9a6b80f # v0.4.2
              id: slither
              with:
                  node-version: 20
                  sarif: results.sarif
                  fail-on: none

            - name: Upload SARIF file
              uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13 # v4.35.1
              with:
                  sarif_file: ${{ steps.slither.outputs.sarif }}